### ISSUE TITLE
Cannot check if the sheet already exist and is empty ?

### ISSUE THREAD

**Issue by Bounti** [caoruiy/excel-python#1]
Hi,

First of all, thank you for you work.

I get stuck because I could not check if the file was opened or created.

So, when I tried to access to a specific sheet I got an exception....
An I have no way to check if the sheet exist or not and if the file was newly created...

A function returning the value of self._file_exist into Excel class should be enough to overcome this issue.

Thank you !

**Comment by caoruiy** [comment]
I omitted on this issue, thank you for your commit. Your new method is very nice
But, You don't need to think about whether the file exists or not, because I provide the  parameter **rebuild**  when you  instantiate the Excel object,  if you want to re-create the file when this file exist,  you can set this parameter to **True**.  By default **False**, Excel object will help you create the new file even the inexistence path of your file dir. 
I don't know you need to determine whether a file exists in what circumstances?

**Comment by Bounti** [comment]
There is no way to know if the file exist or will be created.

When running for the first time my script, the Excel file does not exist. If I called the read() method I will get an exception. So file_exist() permits to know if the file will be created or is already present.
And then, I can do different actions on the Excel file.

Thank for adding the commit to your main branch.
